import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="bg-gray-900 min-h-screen text-white">
      <NavBar />
      <main>{children}</main>
    </div>
      </body>
    </html>
  );
}
